apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: security-headers
  namespace: traefik-system
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/component: middleware
spec:
  headers:
    browserXssFilter: true
    contentTypeNosniff: true # anti MIME-type sniff
    forceSTSHeader: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 31536000
    frameDeny: true # anti clickjacking
    customFrameOptionsValue: "SAMEORIGIN"
    referrerPolicy: "same-origin" # Referrer limit
    customResponseHeaders: # remove traefik version info
      X-Robots-Tag: "noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex"
      Server: ""  # Hide server version
      X-Powered-By: "AICC-MLOps-MAV"

