apiVersion: v1
kind: Namespace
metadata:
  name: jupyterhub
  labels:
    name: jupyterhub
    pod-security.kubernetes.io/enforce: baseline #modify
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: gpu-quota
  namespace: jupyterhub
spec:
  hard:
    requests.nvidia.com/gpu: "4"
    limits.nvidia.com/gpu: "4"
    requests.cpu: "20"
    requests.memory: 64G
    limits.cpu: "40"
    limits.memory: 96G
    persistentvolumeclaims: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: gpu-limitrange
  namespace: jupyterhub
spec:
  limits:
  - type: Container
    max:
      cpu: "8"
      memory: 32G
      # GPU limit by ResourceQuota 
    min:
      cpu: 100m
      memory: 128M
    default:
      cpu: "1"
      memory: 2G
    defaultRequest:
      cpu: 500m
      memory: 1G
  - type: Pod
    max:
      cpu: "16"
      memory: 64G
    min:
      cpu: 100m
      memory: 128M
